# loading in libraries

library(plyr)
library(tidyverse)
library(ggplot2)
library(ggforce)
library(ggthemes)
library(readr)
library(readxl)
library(tibble)
library(rvest)
library(XML)
library(RCurl)
library(rlist)
library(ggrepel)
library(shiny)
library(plotly)
library(gt)
library(rpart)
library(rpart.plot)

# reading in data from different .R file to reduce clutter

source("forbes.R",local = TRUE)

ui <- navbarPage(
    "Buddy Ball: Understanding NBA Finances Amidst COVID-19",
    
    tabPanel("Introduction", 
             h3("Project Background and Motivations"),
             p("This project will analyze the potential ramifications of the 
             ongoing COVID-19 pandemic on the finances of National Basketball
             Association (NBA) teams. NBA Commissioner Adam Silver revealed in 
             May 2020 that ticket sales for in-person fan attendance comprises 
             an estimated 40% of the NBA’s revenue. In a doomdsay scenario that 
             would have no fans in the arenas for the 2020-2021, both the 
             players’ and the owners’ share of Basketball Related Income would 
             decrease from roughly $4 billion to $2.4 billion according to 
             Silver's projection. If this is the case, the league will have to 
             rethink its entire business model. The commisioner has already 
             discussed the possibility of the league turning to sports betting, 
             serving hard alcohol at games, and casinos (long thought of by the 
             league as sinful endeavours) as a way to get cash into the hands 
             of teams. This project will take a deep dive of the most recent 
             update on each team's finances to better understand the situations 
             and constraints each individual team faces in the COVID-19 
             world."),
             br(), 
             p("This is a video of one of the greatest buzzer-beater shots in 
               NBA history. This analysis is being done to better understand
               the new normal we are in that involves limited to no fans in 
               arenas, but hopefully we will get back to jubilant moments like 
               this one soon."),
             
             # Most of this code is generated by YouTube. All I did was to 
             # change the height and weight arguments to fit the screen best.
             
             HTML('<iframe width="1000" height="500" 
                  src="https://www.youtube.com/embed/a-M3x-eZpV8" 
                  frameborder="0" allow="accelerometer; autoplay; 
                  clipboard-write; encrypted-media; gyroscope; 
                  picture-in-picture" allowfullscreen></iframe>'),
             ),
    
    tabPanel("Methodology",
             h3("Data Sources"),
             p("Most of this data comes from the Forbes February 2020 NBA Team
               Valuations publication. Other data comes from spreadsheets that I
               maintain in my free time (the link to those spreadsheets is at 
               the bottom of the page."),
             br(),
             h3("Explanation of Variables in Dataset"),
             p("team: Abbreviation of team name"),
             p("value_change: Percentage change in team's valuation between
               February 2019 and February 2020"),
             p("year_purchased: Year current ownership group purchased team"),
             p("price_paid: Price (in millions) that current ownership group
               paid when they bought the team"),
             p("gate_receipts: Amount (in millions) that team brings in 
               through fan attendance"),
             p("metro_area_pop: Population (in millions) of metropolitan area"),
             p("sport: Portion of franchise's value attributable to revenue 
               shared among all teams"),
             p("market: Portion of franchise's value attributable to its city 
               and market size"),
             p("stadium: Portion of franchise's value attributable to its 
               arena"),
             p("brand: Portion of franchise's value attributable to its brand"),
             p("avg_ticket: Average ticket price"),
             p("build_cost: Amount (in millions) that arena cost to build"),
             p("valuation: Team's valuation (in millions)"),
             p("debt_to_value: Debt divided by value, including arena debt"),
             p("revenue: Amount of revenue (in millions)"),
             p("operating_income: Earnings before interest, taxes, etc."),
             p("sport_pct: Percentage of franchise's value attributable to 
               revenue shared among all teams"),
             p("market_pct: Percentage of franchise's value attributable to
               its city and market size"),
             p("stadium_pct: Percentage of franchise's value attributable to 
               its arena"),
             p("brand_pct: Percentage of franchise's value attributable to its 
               brand"),
             p("growth_rate: Team's valuation minus price paid, divded by 
               difference between 2020 and year purchased"),
             p("income_no_fans: The operating income for a franchise, minus 
               the gate receipts that they project to lose with zero fan 
               attendance"),
             p("revenue_no_fans: The revenue for a franchise, minus 
               the gate receipts that they project to lose with zero fan 
               attendance"),
             ),
    
    tabPanel("Plots",
             p("This section allows you to plot two variables with each 
               other, either as a scatterplot or bar graph. Please reference
               the methodology tab for explanations of what the variables
               represent."),
             br(),
             
             fluidPage(
                 selectInput("x", "X variable", 
                             choices = names(full_dataset_condensed)),
                 selectInput("y", "Y variable", 
                             choices = names(full_dataset_condensed)),
                 selectInput("geom", "geom", c("point", "column")),
                 plotOutput("plot1")),
             br(),
             br(),
             br(),
             
             p("This is a plot of raw team valuations. As you can see, team 
               values range from the New York Knicks worth $4.6 billion to 
               the Memphis Grizzlies worth less than a third of that at 
               $1.3 billion."),
             br(),
             plotOutput("plot2"), 
             br(),
             br(),
             br(),
             
             p("This is a plot of the growth rate of team valuations, 
               calculated as (valuation - price_paid)/(2020-year_purchased). 
               Every team has experienced positive growth rates since they were
               last purchased except for the Brooklyn Nets, who were purchased
               in 2019 for $3.3 billion for nearly a billion dollar premium by 
               the co-founder of Alibaba, and will probably cross the $3.3 
               billion threshold soon barring a worse-case COVID-19 scenario."),
             br(),
             plotOutput("plot3"),
             br(),
             br(),
             br(),
             
             p("This is a plot of the raw values of the four components of
               a team's valuation."),
             br(),
             plotOutput("plot4"),
             br(),
             br(),
             br(),
             
             p("This is a plot of the percentage breakdowns of the four
               components of a team's valuation. This plot is probably 
               preferable to the previous one because it standardizes the 
               values to make them non-dependent on the magnitude of a team's 
               valuation."),
             br(),
             plotOutput("plot5"), 
             br(),
             br(),
             br(),
             
             p("This is a plot of teams in order of how much of their valuation
               is attributable to revenue sharing among the teams. It is clear 
               that smaller market teams rely much more on general revenue from the 
               legaue than the big market teams, who actually lose money from the 
               revenue sharing system."),
             br(),
             plotOutput("plot6"),
             br(),
             br(),
             br(),
             
             p("This is a scatterplot of team valuations and gate receipts. 
               There is a very strong positive correlation between the 
               two variables, showcasing the greater reliance on gate receipts
               for richer teams even after controlling for the magnitude of
               team valuation."),
             plotOutput("plot7"),
             br(),
             br(),
             br(),
             
             p("This is a scatterplot of team valuation and the percentage 
               of a team's valuation attributable to their stadium. There is a 
               moderate strong positive correlation between the two variables, 
               showcasing the greater reliance on the value of their stadium 
               for richer teams as opposed to the revenue sharing component 
               from the league."),
             br(),
             plotOutput("plot8"),
             br()
             
    ),
    
    tabPanel("Model",
             h3("Standard Generalized Linear Model Output"),
             uiOutput("equation1"),
             br(),
             gt_output(outputId = "table4"),
             br(),
             h4("Interpretation of Stan GLM"),
             p("The purpose of creating this 'model' is to attempt to quantify 
               the importance of gate receipts to a team's revenue. The actual 
               median estimate is not necessarily important; rather, the fact 
               that we are 95% confident that coefficients lies well greater
               than 0. The key interpretation is the beta of the gate receipts 
               variable: 1.21. This coefficient can be interpreted as that a 
               $1.00 decrease in gate receipts is associated with a $1.21 
               decrease in revenue, holding all else constant. Again, this 
               coefficient is undoubtedly inaccurate, but the point of running
               this Standard GLM and displaying the table is to ascertain the 
               importance of gate receipts in the NBA's business model."),
             br(),
             h3("Regression Trees"),
             uiOutput("equation2"),
             uiOutput("equation3"),
             splitLayout(cellWidths = c("50%", "50%"),
                         plotOutput("plot12"),
                         plotOutput("plot13")
             ),
             h4("Interpretation of Regression Trees"),
             p("These regression trees are pretty complex and their complete 
               interpretation is beyond both the scope of this project and of 
               this class. Similar to the standard generalized linear model 
               included above, the inclusion of the regression trees is to 
               understand ")
    ),
    
    
             

    
    tabPanel("Three Case Studies",
             tabsetPanel(type = "tabs", 
                         tabPanel("Golden State Warriors (Big Market)", 
                                  splitLayout(cellWidths = c("50%", "50%"),
                                              imageOutput("myImage2"),
                                              gt_output(outputId = "table1")
                                  ),
                                  br(),
                                  br(),
                                  br(),
                                  br(),
                                  br(),
                                  plotOutput("plot9")
                                  ), 
                         tabPanel("Portland Trail Blazers (Middle Market)", 
                                  splitLayout(cellWidths = c("50%", "50%"),
                                              imageOutput("myImage3"),
                                              gt_output(outputId = "table2")
                                  ),
                                  br(),
                                  br(),
                                  br(),
                                  br(),
                                  br(),
                                  plotOutput("plot10")
                         ), 
                         tabPanel("Memphis Grizzlies (Small Market)", 
                                  splitLayout(cellWidths = c("50%", "50%"),
                                              imageOutput("myImage4"),
                                              gt_output(outputId = "table3")
                                  ),
                                  br(),
                                  br(),
                                  br(),
                                  br(),
                                  br(),
                                  plotOutput("plot11")
                         )
                         )
             ),
            
    tabPanel("Discussion",
             p("This will be a discussion about what the model shows as well as 
             potential policy suggestions to mitigate this potential damage."),
             ),
    
    tabPanel("About",
             h3("About Me"),
             p("My name is Buddy Scott and I concentrate in Economics with a 
               secondary in Government at Harvard College. I am a setter on the 
               Men's Volleyball team, the Editor in Chief for the Harvard 
               Sports Analysis Collective, and a Spring 2021 Intern at the 
               National Basketball Players Association (NBPA). You can reach me 
               at jamesscott@college.harvard.edu."), 
             imageOutput("myImage1"),
             br(),
             br(),
             br(),
             br(),
             br(),
             br(),
             a("Connect with me on LinkedIn", 
               href = "https://www.linkedin.com/in/buddyscott13/"),
             br(),
             a("Please see my GitHub repo here", 
               href = "https://github.com/buddyscott/nba-team-business-models"),
             br(), 
             a("Please see my NBA spreadsheet work here", 
               href = "https://hu-my.sharepoint.com/:x:/g/personal/jamesscott_college_harvard_edu/Ees1sxrxTG1AobHhy3Z_SEEBxzYTcnAFO1zm5XM22L-JGQ?e=gfcWXM")
    ))


    
    # Define server logic
    server <- function(input, output, session) {
        
        # This corresponds to the fluidPage() code above that allows the user 
        # to make the plot that they so choose. The syntax here was pretty
        # straight forward.
        
        output$full_dataset_condensed = DT::renderDataTable({
            full_dataset_condensed
        })
        
        plot_geom <- reactive({
            switch(input$geom,
                   point = geom_point(),
                   column = geom_col()
            )
        })

        output$plot1 <- renderPlot({
            ggplot(full_dataset_condensed, aes(.data[[input$x]], 
                                               .data[[input$y]])) +
                plot_geom() + theme_bw() + geom_smooth(formula = y ~ x)
                
        }, res = 96)
        
        output$plot2 <- 
            renderPlot({
                full_dataset_condensed %>%
                    ggplot(aes(x = fct_reorder(team, valuation), y = valuation)) + 
                    geom_col() + 
                    scale_y_continuous(breaks = c(1000, 2000, 3000, 4000, 5000), 
                                       labels = c("$1B", "$2B", "$3B", "$4B", 
                                                  "$5B")) + 
                    theme(axis.text = element_text(size = 8)) +
                    labs(title = "Team Valuations", 
                         x = "Team", y = "Valuation") + 
                    coord_flip() + 
                    theme_classic()
            })
        
        output$plot3 <- 
            renderPlot({
                full_dataset_condensed %>%
                    ggplot(aes(x = fct_reorder(team, growth_rate), 
                               y = growth_rate)) + 
                    geom_col() + 
                    coord_flip() + 
                    theme_classic() + 
                    labs(title = "Valuation Growth Rate by Team", x = "Team", 
                         y = "Growth Rate (Dollars per Year)") + 
                    scale_y_continuous(breaks = c(-800, -400, 0, 400), 
                                       labels = c("-$800M", "-$400M", "$0", 
                                                  "$400M"))
            })
        
        
        output$plot4 <- 
            renderPlot({
                pivoted_raw_dataset %>%
                    ggplot(aes(x = aspect, y = values)) + 
                    geom_col() + 
                    facet_wrap(~ team, ncol = 6) + 
                    theme(strip.text = element_text(size = 6), 
                          axis.text = element_text(size = 4), 
                          panel.grid = element_blank(), 
                          panel.spacing.x = unit(3, "mm")) + 
                    labs(title = "Team Valuation Breakdown", 
                         x = "Raw Valuation Breakdown", 
                         y = "Dollars") +
                    scale_x_discrete(breaks = c("brand", "market", 
                                                "sport", "stadium"), 
                                     labels = c("Brand", "Market", 
                                                "Sport", "Stadium")) + 
                    scale_y_continuous(breaks = c(500, 1000, 1500, 2000), 
                                       labels = c("$500M", "$1B", "$1.5B", 
                                                  "$2B")) + 
                    theme_classic()
            })
        
        
        output$plot5 <- 
            renderPlot({
                pivoted_pct_dataset %>%
                    ggplot(aes(x = aspect, y = values)) + 
                    geom_col() + 
                    facet_wrap(~ team, ncol = 6) + 
                    theme(strip.text = element_text(size = 6), 
                          axis.text = element_text(size = 4), 
                          panel.grid = element_blank(), 
                          panel.spacing.x = unit(3, "mm")) + 
                    labs(title = "Team Valuation Breakdown", 
                         x = "Percent Valuation Breakdown", 
                         y = "Percentage") +
                    scale_x_discrete(breaks = c("brand_pct", "market_pct", 
                                                "sport_pct", "stadium_pct"), 
                                     labels = c("Brand", "Market", 
                                                "Sport", "Stadium")) + 
                    scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6), 
                                       labels = c("0%", "20%", "40%", "60%")) + 
                    theme_classic()
            })
        
        output$plot6 <- 
            renderPlot({
                full_dataset_condensed %>%
                    ggplot(aes(x = fct_reorder(team, sport_pct), 
                               y = sport_pct)) + 
                    geom_col() + 
                    theme(axis.text = element_text(size = 8)) +
                    labs(title = "Sport Percentages by Team", 
                         x = "Team", y = "Sport Percentage") + 
                    scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6), 
                                       labels = c("0%", "20%", "40%", "60%")) + 
                    coord_flip() + 
                    theme_classic()
                
            })
        
        output$plot7 <- 
            renderPlot({
                full_dataset_condensed %>%
                    ggplot(aes(x = valuation, y = gate_receipts)) + 
                    geom_point() + 
                    geom_text_repel(aes(label = team)) + 
                    geom_smooth(formula = y ~ x) + 
                    labs(title = "Team Valuation vs. Gate Receipts", 
                         subtitle = "Correlation = 0.81", x = "Team Valuation", 
                         y = "Gate Receipts") + 
                    theme_bw() + 
                    scale_y_continuous(breaks = c(0, 50, 100, 150, 200), 
                                       label = c("$0", "$50M", "$100M", "$150M", 
                                                 "$200M")) + 
                    scale_x_continuous(breaks = c(1000, 2000, 3000, 4000, 5000), 
                                       label = c("$1B", "$2B", "$3B", "$4B", 
                                                 "$5B"))
                
            })
        
        output$plot8 <- 
            renderPlot({
        full_dataset_condensed %>%
            ggplot(aes(x = valuation, y = stadium_pct)) + 
            geom_point() + 
            geom_text_repel(aes(label = team)) + 
            geom_smooth(formula = y ~ x) + 
        labs(title = "Team Valuation vs. Valuation % Attributable to Staduium", 
                 subtitle = "Correlation = 0.53", x = "Team Valuation", 
                 y = "Stadium Percentage") + 
            theme_bw() + 
            scale_y_continuous(breaks = c(0, 0.1, 0.2, 0.3), 
                               label = c("0%", "10%", "20%", "30%")) + 
            scale_x_continuous(breaks = c(1000, 2000, 3000, 4000, 5000), 
                               label = c("$1B", "$2B", "$3B", "$4B", "$5B"))
            })
        
        output$plot9 <- 
            renderPlot({
        pivoted_pct_dataset_gsw %>%
            ggplot(aes(x = aspect, y = values)) + 
            geom_col() + 
            theme(strip.text = element_text(size = 6), 
                  axis.text = element_text(size = 4), 
                  panel.grid = element_blank(), 
                  panel.spacing.x = unit(3, "mm")) + 
            labs(title = "Team Valuation Breakdown", 
                 x = "Percent Valuation Breakdown", 
                 y = "Percentage") +
            scale_x_discrete(breaks = c("brand_pct", "market_pct", 
                                        "sport_pct", "stadium_pct"), 
                             labels = c("Brand", "Market", 
                                        "Sport", "Stadium")) + 
            scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6), 
                               labels = c("0%", "20%", "40%", "60%")) + 
            theme_classic()
            })
        
        output$plot10 <- 
            renderPlot({
                pivoted_pct_dataset_por %>%
                    ggplot(aes(x = aspect, y = values)) + 
                    geom_col() + 
                    theme(strip.text = element_text(size = 6), 
                          axis.text = element_text(size = 4), 
                          panel.grid = element_blank(), 
                          panel.spacing.x = unit(3, "mm")) + 
                    labs(title = "Team Valuation Breakdown", 
                         x = "Percent Valuation Breakdown", 
                         y = "Percentage") +
                    scale_x_discrete(breaks = c("brand_pct", "market_pct", 
                                                "sport_pct", "stadium_pct"), 
                                     labels = c("Brand", "Market", 
                                                "Sport", "Stadium")) + 
                    scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6), 
                                       labels = c("0%", "20%", "40%", "60%")) + 
                    theme_classic()
            })
        
        output$plot11 <- 
            renderPlot({
                pivoted_pct_dataset_mem %>%
                    ggplot(aes(x = aspect, y = values)) + 
                    geom_col() + 
                    theme(strip.text = element_text(size = 6), 
                          axis.text = element_text(size = 4), 
                          panel.grid = element_blank(), 
                          panel.spacing.x = unit(3, "mm")) + 
                    labs(title = "Team Valuation Breakdown", 
                         x = "Percent Valuation Breakdown", 
                         y = "Percentage") +
                    scale_x_discrete(breaks = c("brand_pct", "market_pct", 
                                                "sport_pct", "stadium_pct"), 
                                     labels = c("Brand", "Market", 
                                                "Sport", "Stadium")) + 
                    scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6), 
                                       labels = c("0%", "20%", "40%", "60%")) + 
                    theme_classic()
            })
        
        output$plot12 <- 
            renderPlot({
                rpart.plot(revenue_tree, type = 2)
            })
        
        output$plot13 <- 
            renderPlot({
                rpart.plot(valuation_tree, type = 2)
            })
        
        
        output$myImage1 <- 
            renderImage({
            list(src = "pictures/headshot.png",
                 width = 300,
                 height = 500,
                 alt = "This is alternate text")
        }, deleteFile = FALSE)
        
        output$myImage2 <- 
            renderImage({
                list(src = "pictures/gsw.png",
                     width = 300,
                     height = 400,
                     alt = "This is alternate text")
            }, deleteFile = FALSE)
        
        output$myImage3 <- 
            renderImage({
                list(src = "pictures/por.png",
                     width = 300,
                     height = 400,
                     alt = "This is alternate text")
            }, deleteFile = FALSE)
        
        output$myImage4 <- 
            renderImage({
                list(src = "pictures/mem.png",
                     width = 300,
                     height = 400,
                     alt = "This is alternate text")
            }, deleteFile = FALSE)
        
        output$table1 <- 
            render_gt(
                
                tibble(subject = c("Valuation", "Metro Area Population", 
                                   "Operating Income", "Revenue", "Gate Receipts",
                                   "Average Ticket Price", "Brand Percentage", 
                                   "Market Percentage", 
                                   "Stadium Percentage", "Sport Percentage", 
                                   "Operating Income - Gate Receipts", 
                                   "Revenue - Gate Receipts"), 
                       beta = c("$4.3B", "7.0M", "$109M", "$440M", "$178M", "$125", 
                                "16.79%", "38.86%", "24.84%", "19.51%", 
                                "-$69M", "$262M"), 
                       `95% CI` = c("3rd", "7th", "4th", "2nd", "1st", "3rd", 
                                    "2nd", "3rd", "2nd", "28th", "29th", "3rd")) %>%
                    gt() %>%
                    cols_label(subject = "Variable", beta = "Value", 
                               `95% CI` = "League Rank") %>%
                    tab_style(cell_borders(sides = "right"), 
                              location = cells_body(columns = vars(subject))) %>%
                    tab_style(cell_text(weight = "bold"),
                              location = cells_body(columns = vars(subject))) %>%
                    cols_align(align = "center", columns = TRUE) %>%
                    fmt_markdown(columns = TRUE) %>%
                    tab_header(title = "Golden State Warriors Financials")
            )
        
        output$table2 <- 
            render_gt(
                
                tibble(subject = c("Valuation", "Metro Area Population", 
                                   "Operating Income", "Revenue", "Gate Receipts",
                                   "Average Ticket Price", "Brand Percentage", 
                                   "Market Percentage", 
                                   "Stadium Percentage", "Sport Percentage", 
                                   "Operating Income - Gate Receipts", 
                                   "Revenue - Gate Receipts"), 
                       beta = c("$1.85B", "2.4M", "$51M", "$287M", "$67M", "$66", 
                                "9.73%", "26.38%", "19.68%", "44.22%", 
                                "-$16M", "$220M"), 
                       `95% CI` = c("13th", "T-21st", "22nd", "13th", "11th", 
                                    "19th", 
                                    "15th", "19th", "9th", "15th", "25th", 
                                    "13th")) %>%
                    gt() %>%
                    cols_label(subject = "Variable", beta = "Value", 
                               `95% CI` = "League Rank") %>%
                    tab_style(cell_borders(sides = "right"), 
                              location = cells_body(columns = vars(subject))) %>%
                    tab_style(cell_text(weight = "bold"),
                              location = cells_body(columns = vars(subject))) %>%
                    cols_align(align = "center", columns = TRUE) %>%
                    fmt_markdown(columns = TRUE) %>%
                    tab_header(title = "Portland Trail Blazers Financials")
            )
        
        output$table3 <- 
            render_gt(
                
                tibble(subject = c("Valuation", "Metro Area Population", 
                                   "Operating Income", "Revenue", "Gate Receipts",
                                   "Average Ticket Price", "Brand Percentage", 
                                   "Market Percentage", 
                                   "Stadium Percentage", "Sport Percentage", 
                                   "Operating Income - Gate Receipts", 
                                   "Revenue - Gate Receipts"), 
                       beta = c("$1.3B", "1.4M", "$24M", "$224M", "$20M", "$35", 
                                "5.77%", "20.15%", "8.92%", "65.15%", 
                                "$4M", "$204M"), 
                       `95% CI` = c("30th", "T-27th", "29th", "T-29th", "30th", 
                                    "T-29th", 
                                    "30th", "28th", "30th", "1st", "20th", 
                                    "25th")) %>%
                    gt() %>%
                    cols_label(subject = "Variable", beta = "Value", 
                               `95% CI` = "League Rank") %>%
                    tab_style(cell_borders(sides = "right"), 
                              location = cells_body(columns = vars(subject))) %>%
                    tab_style(cell_text(weight = "bold"),
                              location = cells_body(columns = vars(subject))) %>%
                    cols_align(align = "center", columns = TRUE) %>%
                    fmt_markdown(columns = TRUE) %>%
                    tab_header(title = "Memphis Grizzlies Financials")
            )
        
        output$table4 <- 
            render_gt(
        
        tibble(subject = c("Intercept", "Gate Receipts", "Operating Income", "Metro Area Population"), 
               beta = c("168.18", "1.21", "0.45", "2.52"), 
               `95% CI` = c("154.59, 181.34", "0.987, 1.417", "0.256, 0.653", "1.174, 3.890")) %>%
            gt() %>%
            cols_label(subject = "Variable", beta = "Beta", 
                       `95% CI` = "95% CI") %>%
            tab_style(cell_borders(sides = "right"), 
                      location = cells_body(columns = vars(subject))) %>%
            tab_style(cell_text(weight = "bold"),
                      location = cells_body(columns = vars(subject))) %>%
            cols_align(align = "center", columns = TRUE) %>%
            fmt_markdown(columns = TRUE) %>%
            tab_header(title = "Regression of Revenue on Variables of Interest", 
                       subtitle = "Focusing on coefficient of gate_receipts") %>%
            tab_footnote(footnote = "CI = Confidence Interval", 
                         locations = cells_column_labels(columns = vars(`95% CI`)))
            )
        
        output$equation1 <- 
            renderUI({
                withMathJax(helpText('Stan GLM Regression Equation: $$revenue_i = \\beta_0 + \\beta_1 gatereceipts_{i} + \\beta_2 operatingincome_{i} + \\beta_3 metroareapop_{i} +  \\epsilon_i $$'))
            })
        
        output$equation2<- 
            renderUI({
                withMathJax(helpText('Regression Equation on Left: $$revenue_i = \\beta_0 + \\beta_1 gatereceipts_{i} + \\beta_2 operatingincome_{i} + \\beta_3 metroareapop_{i} +  \\epsilon_i $$'))
            })
        
        output$equation3 <- 
            renderUI({
                withMathJax(helpText('Regression Equation on Right: $$valuation_i = \\beta_0 + \\beta_1 brand_{i} + \\beta_2 market_{i} + \\beta_3 stadium_{i} + \\beta_4 sport_{i} + \\epsilon_i $$'))
            })
        
        
        
    }
    
    shinyApp(ui, server)
    
    
    

    
    