```{r}
library(plyr)
library(tidyverse)
library(ggplot2)
library(ggrepel)
library(ggforce)
library(ggthemes)
library(readr)
library(readxl)
library(tibble)
library(rvest)
library(XML)
library(RCurl)
library(rlist)
library(rstanarm)
library(rsample)
library(ggridges)
library(rpart)
library(rpart.plot)
library(neuralnet)
```

```{r}
nbainfo <- read_csv("data-files/nbainfo.csv", 
                    col_type = cols(team = col_character(), 
                                    "1920winpct" = col_number(), 
                                    winpctrank = col_number(), 
                                    "1920ortg" = col_number(),
                                    ortgrank = col_number(), 
                                    "1920drtg" = col_number(), 
                                    drtgrank = col_number(), 
                                    "1920nrtg" = col_number(), 
                                    nrtgrank = col_number(), 
                                    "1920pace" = col_number(), 
                                    pacerank = col_number(), 
                                    gtcontracts = col_number(), 
                                    po_ngs = col_number(), 
                                    avgage = col_number(), 
                                    medage = col_number(), 
                                    avgexp = col_number(), 
                                    medexp = col_number(), 
                                    "2021projsalary" = col_number(), 
                                    "2021projcapspace" = col_number(), 
                                    "2021projexceptions" = col_character(), 
                                    tenyrwin = col_number(), 
                                    tenyrloss = col_number(), 
                                    tenyrwinpct = col_number(), 
                                    winpctrank_10 = col_number(), 
                                    playoffpct = col_number(), 
                                    principal_owner = col_character(), 
                                    nw = col_number(), 
                                    owned_since = col_number(), 
                                    business = col_character(), 
                                    other_owners = col_character(), 
                                    valuation = col_number(), 
                                    percent_change = col_number(), 
                                    debt_to_value = col_number(), 
                                    revenue = col_number(), 
                                    operating_income = col_number())) %>%
    rename_with(~ str_replace(.x, "1920", "lastseason")) %>% 
    rename_with(~ str_replace(.x, "2021", "nextseason")) %>% 
    slice(1:30) %>%
    subset(select = -nextseasonprojcapspace) %>%
    select(team, lastseasonwinpct, lastseasonortg, lastseasondrtg, 
           lastseasonnrtg, lastseasonpace, gtcontracts, avgage, medage, avgexp,
           medexp, nextseasonprojsalary, nextseasonprojexceptions, 
           tenyrwinpct, playoffpct, principal_owner, nw, valuation, 
           percent_change, debt_to_value, revenue, operating_income)

playercontracts <- read_csv("data-files/bbrefcontractdata.csv", col_type = cols(
  playername = col_character(),
  playerid = col_character(),
  team = col_character(),
  salary1920 = col_double(),
  salary2021 = col_double(),
  salary2122 = col_double(),
  salary2223 = col_double(),
  salary2324 = col_double(),
  salary2425 = col_double(),
  signedusing = col_character(),
  guaranteed = col_double())) %>%
  filter(!is.na(salary2021)) %>%
  subset(select = -c(salary1920, guaranteed)) %>%
  mutate(pctsalary2021 = salary2021 / 109140000)

playercontracts_modified <- playercontracts %>%
  filter(!is.na(salary2021)) %>%
  filter(salary2021 > (109140000*0.15))

forbes1 <- read_csv("data-files/forbes2020.csv", 
                    col_type = cols(.default = col_character())) %>%
  mutate(rank = str_sub(rank, start = 2)) %>%
  mutate(valuation = substr(valuation, 2, nchar(valuation)-1)) %>%
  mutate(value_change = gsub('.{1}$', '', value_change)) %>%
  mutate(debt_to_value = gsub('.{1}$', '', debt_to_value)) %>%
  mutate(revenue = substr(revenue, 2, nchar(revenue)-1)) %>%
  mutate(operating_income = substr(operating_income, 2, 
                                   nchar(operating_income)-1)) %>%
  mutate(rank = as.numeric(rank)) %>%
  mutate(valuation = as.numeric(valuation)) %>%
  mutate(value_change = as.numeric(value_change)) %>%
  mutate(debt_to_value = as.numeric(debt_to_value)) %>%
  mutate(revenue = as.numeric(revenue)) %>%
  mutate(operating_income = as.numeric(operating_income)) %>%
  subset(select = -rank)

forbes2 <- read_csv("data-files/moreforbes.csv", 
                    col_type = cols(.default = col_double(), 
                                    team = col_character()))

forbes_joined <- inner_join(forbes1, forbes2, by = "team")

full_dataset <- inner_join(forbes_joined, nbainfo, by = "team") %>%
    subset(select = -c(valuation.y, debt_to_value.y, revenue.y, 
                       operating_income.y, percent_change)) %>%
    mutate(valuation = valuation.x) %>%
    mutate(debt_to_value = debt_to_value.x) %>%
    mutate(revenue = revenue.x) %>%
    mutate(operating_income = operating_income.x) %>%
    subset(select = -c(valuation.x, debt_to_value.x, revenue.x, 
                       operating_income.x)) %>%
    mutate(valuation = valuation*1000) %>%
    mutate(sport_pct = sport/valuation) %>%
    mutate(market_pct = market/valuation) %>%
    mutate(stadium_pct = stadium/valuation) %>%
    mutate(brand_pct = brand/valuation) %>%
    mutate(growth_rate = (valuation-price_paid)/(2020-year_purchased)) %>%
    mutate(income_no_fans = operating_income - gate_receipts) %>%
    mutate(revenue_no_fans = revenue - gate_receipts)


breakdown <- c(full_dataset$sport_pct, full_dataset$market_pct, 
                        full_dataset$stadium_pct, full_dataset$brand_pct)
  
                    
```

```{r}
write.csv(full_dataset,"data-files/full_dataset.csv", row.names = FALSE)
```

```{r}
full_dataset %>%
  select(team, sport_pct, market_pct, stadium_pct, brand_pct) %>%
  arrange(desc(brand_pct))
```


```{r}

round(cor(full_dataset$metro_area_pop, full_dataset$valuation), 2)
round(cor(full_dataset$year_purchased, full_dataset$price_paid), 2)
round(cor(full_dataset$metro_area_pop, full_dataset$operating_income), 2)
round(cor(full_dataset$metro_area_pop, full_dataset$revenue), 2)

                full_dataset %>%
                    ggplot(aes(x = fct_reorder(team, valuation), y = valuation)) + 
                    geom_col() + 
                    scale_y_continuous(breaks = c(1000, 2000, 3000, 4000, 5000), 
                                       labels = c("$1B", "$2B", "$3B", "$4B", 
                                                  "$5B")) + 
                    theme(axis.text = element_text(size = 8)) +
                    labs(title = "Team Valuations", 
                         x = "Team", y = "Valuation") + 
                    coord_flip() + 
                    theme_classic()
                
full_dataset %>%
  ggplot(aes(x = fct_reorder(team, growth_rate), y = growth_rate)) + 
  geom_col() + 
  coord_flip() + 
  theme_classic() + 
  labs(title = "Valuation Growth Rate by Team", x = "Team", 
       y = "Growth Rate (Dollars per Year)") + 
  scale_y_continuous(breaks = c(-800, -400, 0, 400), labels = c("-$800M", 
                                                               "-$400M", 
                                                               "$0", "$400M"))

full_dataset %>%
  ggplot(aes(x = metro_area_pop, y = valuation)) + 
  geom_point() + 
  geom_text_repel(aes(label = team)) + 
  geom_smooth(formula = y ~ x) + 
  labs(title = "Metro Area Population vs. Team's Valuation", subtitle = 
         "Correlation = 0.72", x = "Metro Area Population", y = "Valuation") + 
  theme_bw() + 
  scale_x_continuous(breaks = c(0, 5, 10, 15, 20, 25), 
                     label = c("0M", "5M", "10M", "15M", "20M", "25M")) + 
  scale_y_continuous(breaks = c(1, 2, 3, 4, 5), 
                     label = c("$1B", "$2B", "$3B", "$4B", "$5B"))

full_dataset %>%
  ggplot(aes(x = year_purchased, y = price_paid)) + 
  geom_point() + 
  geom_text_repel(aes(label = team)) + 
  geom_smooth(formula = y ~ x) + 
  labs(title = "Franchise's Year Purchased vs. Price Paid", 
       subtitle = "Correlation = 0.72", x = "Year Purchased", 
       y = "Price Paid") + 
  theme_bw() + 
  scale_y_continuous(breaks = c(0, 1000, 2000, 3000), 
                     label = c("$0", "$1B", "$2B", "$3B"))

full_dataset %>%
  ggplot(aes(x = metro_area_pop, y = operating_income)) + 
  geom_point() + 
  geom_text_repel(aes(label = team)) + 
  geom_smooth(formula = y ~ x) + 
  labs(title = "Metro Area Population vs. Opearating Income", 
       subtitle = "Correlation = 0.55", x = "Metro Area Population", 
       y = "Opearating Income") + 
  theme_bw()

full_dataset %>%
  ggplot(aes(x = metro_area_pop, y = revenue)) + 
  geom_point() + 
  geom_text_repel(aes(label = team)) + 
  geom_smooth(formula = y ~ x) + 
  labs(title = "Metro Area Population vs. Revenue", 
       subtitle = "Correlation = 0.65", x = "Metro Area Population", 
       y = "Revenue") + 
  theme_bw()

full_dataset %>%
  ggplot(aes(x = fct_reorder(team, gate_receipts), y = gate_receipts)) + 
  geom_col() + 
  theme(axis.text = element_text(size = 8)) +
  labs(title = "Gate Receipts by Team", x = "Team", y = "Gate Receipts") + 
  coord_flip() + 
  theme_bw() + 
  scale_y_continuous(breaks = c(0, 50, 100, 150, 200), 
                     label = c("$0", "$50M", "$100M", "$150M", "$200M")) 

full_dataset %>%
  ggplot(aes(x = valuation, y = gate_receipts)) + 
  geom_point() + 
  geom_text_repel(aes(label = team)) + 
  geom_smooth(formula = y ~ x) + 
  labs(title = "Team Valuation vs. Gate Receipts", 
       subtitle = "Correlation = 0.65", x = "Team Valuation", 
       y = "Gate Receipts") + 
  theme_bw() + 
  scale_y_continuous(breaks = c(0, 50, 100, 150, 200), 
                     label = c("$0", "$50M", "$100M", "$150M", "$200M")) + 
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5), 
                     label = c("$1B", "$2B", "$3B", "$4B", "$5B"))

pivoted_raw_dataset <- full_dataset %>%
  select(team, valuation, sport, market, stadium, brand) %>%
  pivot_longer(sport:brand, names_to = "aspect", values_to = "values") %>%
  arrange(desc(valuation))

pivoted_raw_dataset %>%
                    ggplot(aes(x = aspect, y = values)) + 
                    geom_col() + 
                    facet_wrap(~ team, ncol = 6) + 
                    theme(strip.text = element_text(size = 6), 
                          axis.text = element_text(size = 4), 
                          panel.grid = element_blank(), 
                          panel.spacing.x = unit(3, "mm")) + 
                    labs(title = "Team Valuation Breakdown", 
                         x = "Raw Valuation Breakdown", 
                         y = "Dollars") +
                    scale_x_discrete(breaks = c("brand", "market", 
                                                "sport", "stadium"), 
                                     labels = c("Brand", "Market", 
                                                "Sport", "Stadium")) + 
                    scale_y_continuous(breaks = c(500, 1000, 1500, 2000), 
                                       labels = c("$500M", "$1B", "$1.5B", 
                                                  "$2B")) + 
                    theme_classic()

pivoted_pct_dataset <- full_dataset %>%
  select(team, valuation, sport_pct, market_pct, stadium_pct, brand_pct) %>%
  pivot_longer(sport_pct:brand_pct, 
               names_to = "aspect", values_to = "values") %>%
  arrange(desc(valuation))

pivoted_pct_dataset %>%
                    ggplot(aes(x = aspect, y = values)) + 
                    geom_col() + 
                    facet_wrap(~ team, ncol = 6) + 
                    theme(strip.text = element_text(size = 6), 
                          axis.text = element_text(size = 4), 
                          panel.grid = element_blank(), 
                          panel.spacing.x = unit(3, "mm")) + 
                    labs(title = "Team Valuation Breakdown", 
                         x = "Percent Valuation Breakdown", 
                         y = "Percentage") +
                    scale_x_discrete(breaks = c("brand_pct", "market_pct", 
                                                "sport_pct", "stadium_pct"), 
                                     labels = c("Brand", "Market", 
                                                "Sport", "Stadium")) + 
                    scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6), 
                                       labels = c("0%", "20%", "40%", "60%")) + 
                    theme_classic()


pivoted_pct_dataset_gsw <- full_dataset %>%
  filter(team == "GSW") %>%
  select(team, valuation, sport_pct, market_pct, stadium_pct, brand_pct) %>%
  pivot_longer(sport_pct:brand_pct, 
               names_to = "aspect", values_to = "values") %>%
  arrange(desc(valuation))

pivoted_pct_dataset_por <- full_dataset %>%
  filter(team == "POR") %>%
  select(team, valuation, sport_pct, market_pct, stadium_pct, brand_pct) %>%
  pivot_longer(sport_pct:brand_pct, 
               names_to = "aspect", values_to = "values") %>%
  arrange(desc(valuation))

pivoted_pct_dataset_mem <- full_dataset %>%
  filter(team == "MEM") %>%
  select(team, valuation, sport_pct, market_pct, stadium_pct, brand_pct) %>%
  pivot_longer(sport_pct:brand_pct, 
               names_to = "aspect", values_to = "values") %>%
  arrange(desc(valuation))

pivoted_pct_dataset_gsw %>%
                    ggplot(aes(x = aspect, y = values)) + 
                    geom_col() + 
                    theme(strip.text = element_text(size = 6), 
                          axis.text = element_text(size = 4), 
                          panel.grid = element_blank(), 
                          panel.spacing.x = unit(3, "mm")) + 
                    labs(title = "Team Valuation Breakdown", 
                         x = "Percent Valuation Breakdown", 
                         y = "Percentage") +
                    scale_x_discrete(breaks = c("brand_pct", "market_pct", 
                                                "sport_pct", "stadium_pct"), 
                                     labels = c("Brand", "Market", 
                                                "Sport", "Stadium")) + 
                    scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6), 
                                       labels = c("0%", "20%", "40%", "60%")) + 
                    theme_classic()

pivoted_pct_dataset_por %>%
                    ggplot(aes(x = aspect, y = values)) + 
                    geom_col() + 
                    theme(strip.text = element_text(size = 6), 
                          axis.text = element_text(size = 4), 
                          panel.grid = element_blank(), 
                          panel.spacing.x = unit(3, "mm")) + 
                    labs(title = "Team Valuation Breakdown", 
                         x = "Percent Valuation Breakdown", 
                         y = "Percentage") +
                    scale_x_discrete(breaks = c("brand_pct", "market_pct", 
                                                "sport_pct", "stadium_pct"), 
                                     labels = c("Brand", "Market", 
                                                "Sport", "Stadium")) + 
                    scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6), 
                                       labels = c("0%", "20%", "40%", "60%")) + 
                    theme_classic()

pivoted_pct_dataset_mem %>%
                    ggplot(aes(x = aspect, y = values)) + 
                    geom_col() + 
                    theme(strip.text = element_text(size = 6), 
                          axis.text = element_text(size = 4), 
                          panel.grid = element_blank(), 
                          panel.spacing.x = unit(3, "mm")) + 
                    labs(title = "Team Valuation Breakdown", 
                         x = "Percent Valuation Breakdown", 
                         y = "Percentage") +
                    scale_x_discrete(breaks = c("brand_pct", "market_pct", 
                                                "sport_pct", "stadium_pct"), 
                                     labels = c("Brand", "Market", 
                                                "Sport", "Stadium")) + 
                    scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6), 
                                       labels = c("0%", "20%", "40%", "60%")) + 
                    theme_classic()

  
```

# Stan GLM Model
```{r}
model_1 <- stan_glm(data = full_dataset, revenue ~ gate_receipts + operating_income + metro_area_pop,
                    family = gaussian(), refresh = 0)

print(model_1, digits = 4)

posterior_interval(model_1, prob = 0.95)
```
```{r}
valuation_tree <- rpart(valuation ~ market + stadium + sport + brand, 
              data = full_dataset, cp = 0.01)
rpart.plot(valuation_tree, type = 2)

revenue_tree <- rpart(revenue ~ operating_income + gate_receipts + 
                metro_area_pop, data = full_dataset, cp = 0.01)
rpart.plot(revenue_tree, type = 2)

```


```{r}
nn=neuralnet(revenue ~ operating_income + gate_receipts + 
               metro_area_pop + avg_ticket, data = full_dataset, hidden=c(5, 2),
             linear.output = TRUE)
plot(nn)
```

```{r}
test_data <- full_dataset
test_data$gate_receipts = 0

prediction_1 <- compute(nn, test_data)
prediction_1$net.result

prediction_2 <- compute(nn, full_dataset)
prediction_2$net.result

```


